image: maven:eclipse-temurin

before_script:
  - cd FullstackProsjekt

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn clean test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml  

package:
  stage: package
  script:
    - mvn clean package
