package idatt2105.group11.idatt2105projectbackend.model;

public enum QuizCategory {
  BUSINESS,
  ART,
  COMPUTER_SCIENCE,
  CULTURE_AND_TRADITIONS,
  FINANCE,
  GENERAL_KNOWLEDGE,
  GEOGRAPHY,
  HISTORY,
  LANGUAGES,
  LAW,
  MATH,
  MUSIC,
  SCIENCE,
  SEASONAL,
  SOCIAL_EMOTIONAL_LEARNING,
  SOCIAL_STUDIES,
  TRIVIA
}
